
CREATE TABLE USERS (
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(100) NOT NULL,
    CREATION_TIME TIMESTAMP 
);



CREATE TABLE CONVERSATION (
    ID SERIAL PRIMARY KEY,
    CONVERSATION_TYPE VARCHAR(20) NOT NULL,
    CONVERSATION_TIMESTAMP TIMESTAMP  
);

CREATE TABLE PARTICIPANTS (
     ID SERIAL PRIMARY KEY,
     CONVERSATION_ID INT REFERENCES CONVERSATION(ID),
     USER_ID INT REFERENCES USERS(ID)
);

CREATE TABLE MESSAGES (
    ID SERIAL PRIMARY KEY,
    SENDER_ID INT REFERENCES USERS(ID),
    CONVERSATION_ID INT REFERENCES CONVERSATION(ID),
    MESSAGE_TYPE VARCHAR(30) NOT NULL,
    content TEXT,
    MESSAGE_TIMESTAMP TIMESTAMP
);

CREATE TABLE MEDIA (
    ID SERIAL PRIMARY KEY,
    MESSAGE_ID INT REFERENCES MESSAGES(ID),
    MEDIA_TYPE VARCHAR(20) NOT NULL,
    MEDIA_PATH VARCHAR(255)
    
);